---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamcity-server.fullname" . }}-environ-secret
  labels:
    {{- include "teamcity-server.labels" . | nindent 4 }}
type: Opaque
data:
  TEAMCITY_DB_PASSWORD: {{ .Values.teamcity.db.password | b64enc }}
stringData:
  TEAMCITY_DB_CONNECTION: {{ .Values.teamcity.db.connectionString }}
